# Site
name: "Brain Problem Games"
description: "Brain Problem Games is a collection of media about Dissociation, Trauma, and identity."
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
baseurl: "/brain-problem-games"
avatar: "assets/images/logo.png"
email: "wowthemesnet@gmail.com"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: GFM
highlighter: rouge

# Pagination
paginate: 20

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
